server:
  port: ${SERVER_PORT:8081}

sync:
  enabled: ${SYNC_ENABLED:true}
  cron.expression: ${SYNC_CRON_EXPRESSION:"0 0 * * *"}

auth:
  providers:
    alfresco:
      type: ${AUTH_ALFRESCO_TYPE}
      username: ${ALFRESCO_USER_NAME}
      password: ${ALFRESCO_PASSWORD}
    hyland-experience:
      type: ${AUTH_HX_TYPE}
      client-id: ${HX_CLIENT_ID}
      client-secret: ${HX_CLIENT_SECRET}
      token-uri: ${HX_TOKEN_URI}
      grant-type: client_credentials
      scope:
        - hxp.integrations
        - iam.user-data.account
        - system-integrations-config
        - system-integrations-runtime
        - environment_authorization
      environment-key: ${HX_ENV_KEY}

alfresco:
  base-url: ${ALFRESCO_BASE_URL}

nucleus:
  idp-base-url: ${NUCLEUS_IDP_BASE_URL}
  base-url: ${NUCLEUS_BASE_URL}
  system-id: ${NUCLEUS_SYSTEM_ID}

logging:
  level:
    org.alfresco.hxi_connector: ${LOGGING_LEVEL_ORG_ALFRESCO:INFO}
    org.springframework.web.reactive.function.client: DEBUG
