server:
  port: ${SERVER_PORT:8081}

sync:
  enabled: ${SYNC_ENABLED:true}
  cron.expression: ${SYNC_CRON_EXPRESSION:"0 0 * * *"}

http-client:
  timeout-minutes: ${HTTP_CLIENT_TIMEOUT_MINUTES:5}
  retry:
    max-attempts: ${HTTP_RETRY_MAX_ATTEMPTS:3}
    initial-delay-ms: ${HTTP_RETRY_INITIAL_DELAY_MS:2000}
    multiplier: ${HTTP_RETRY_MULTIPLIER:2}
    max-delay-ms: ${HTTP_RETRY_MAX_DELAY_MS:10000}

auth:
  providers:
    alfresco:
      type: ${AUTH_ALFRESCO_TYPE}
      username: ${ALFRESCO_USER_NAME}
      password: ${ALFRESCO_PASSWORD}
    hyland-experience:
      type: ${AUTH_HX_TYPE}
      client-id: ${HX_CLIENT_ID}
      client-secret: ${HX_CLIENT_SECRET}
      token-uri: ${HX_TOKEN_URI}
      grant-type: client_credentials
      scope:
        - hxp.integrations
        - iam.user-data.account
        - system-integrations-config
        - system-integrations-runtime
        - environment_authorization

alfresco:
  base-url: ${ALFRESCO_BASE_URL}
  page-size: 1000
  sync-batch-size: 1000
  user-group:
    fetch-timeout: PT5M

nucleus:
  idp-base-url: ${NUCLEUS_IDP_BASE_URL}
  base-url: ${NUCLEUS_BASE_URL}
  system-id: ${NUCLEUS_SYSTEM_ID}
  page-size: 1000
  delete-group-member-batch-size: ${DELETE_BATCH_SIZE:100}

logging:
  level:
    org.alfresco.hxi_connector: ${LOGGING_LEVEL_ORG_ALFRESCO:INFO}
    org.springframework.web.reactive.function.client: DEBUG
